#!/usr/bin/env bash
# farhand watcher: starts jobs in the background and keeps track of them.
# Usage: watcher.sh start <engine> <job>
#        watcher.sh status
set -u

# --- state ------------------------------------------------------------------
# One file per fact, under XDG state. job.pid is the only link between a
# running calculation and any future watcher process.

STATE="${FARHAND_STATE:-${XDG_STATE_HOME:-$HOME/.local/state}/farhand}"
LAUNCH="${FARHAND_LAUNCH:-$(dirname "$0")/../launch/launch.sh}"
mkdir -p "$STATE"

# --- helpers ----------------------------------------------------------------

# alive <pid>: is this pid running, and is it plausibly still our job?
#
# kill -0 only asks whether SOME process has this number. PIDs are recycled, so
# after a reboot that number may belong to an unrelated service -- and adopting
# it would wedge the watcher on a phantom job that no remote command can clear.
# Two cheap checks close that gap: the boot id (a reboot invalidates every pid
# at once) and the command line (the process should still be our launcher).
alive() {
  local pid="$1" boot

  kill -0 "$pid" 2>/dev/null || return 1

  # a reboot means every recorded pid is meaningless
  if [ -f "$STATE/job.boot" ]; then
    boot="$(cat /proc/sys/kernel/random/boot_id 2>/dev/null || true)"
    [ "$boot" = "$(cat "$STATE/job.boot")" ] || return 1
  fi

  # the process should still be the launcher we started
  # TODO (multi-engine): grep for this engine's state dir too, not just
  # launch.sh -- otherwise two watchers could adopt each other's job.
  tr '\0' ' ' < "/proc/$pid/cmdline" 2>/dev/null | grep -q 'launch.sh' || return 1
}

# --- commands ---------------------------------------------------------------
TRIG="$STATE/triggers"
mkdir -p "$TRIG"

# trigger <cmd> <engine> <job>: drop a request file for the watcher to notice.
trigger() {
  local cmd="$1" engine="$2" job="$3" ts
  ts="$(date +%s.%N)"
  touch "$TRIG/$cmd.$engine.$job.$ts"
}

# next_trigger: print "cmd engine job" for the oldest trigger and remove its
# file, or print nothing if the queue is empty.
next_trigger() {
  local f base cmd engine job

  # Trigger filenames are generated by trigger(), never user-supplied, and
  # contain no newlines. ls is fine here and sorts by our embedded timestamp.
  # shellcheck disable=SC2012
  f="$(ls -1 "$TRIG" 2>/dev/null | sort | head -n 1)"
  [ -n "$f" ] || return 1

  rm -f "$TRIG/$f"

  base="$f"
  cmd="${base%%.*}";    base="${base#*.}"
  engine="${base%%.*}"; base="${base#*.}"
  job="${base%%.*}"

  printf '%s %s %s\n' "$cmd" "$engine" "$job"
}

tick() {
  local t cmd engine job

  t="$(next_trigger)" || return 0
  read -r cmd engine job <<< "$t"

  case "$cmd" in
    run) start "$engine" "$job" ;;
    *) echo "watcher: unknown command: $cmd" >&2 ;;
  esac
}


start() {
  local engine="$1" job="$2"

  if [ -f "$STATE/job.pid" ] && alive "$(cat "$STATE/job.pid")"; then
    echo "watcher: busy, job $(cat "$STATE/job.name") is running" >&2
    return 1
  fi

  bash "$LAUNCH" "$engine" "$job" > "$STATE/launch.log" 2>&1 &
  echo "$!" > "$STATE/job.pid"
  echo "$job" > "$STATE/job.name"
  cat /proc/sys/kernel/random/boot_id > "$STATE/job.boot"
  echo "started $job (pid $!)"
}

status() {
  local pid

  if [ ! -f "$STATE/job.pid" ]; then
    echo idle
    return 0
  fi

  pid="$(cat "$STATE/job.pid")"
  if alive "$pid"; then
    echo "running $(cat "$STATE/job.name") (pid $pid)"
  else
    echo "stale: $(cat "$STATE/job.name") (pid $pid) is gone"
  fi
}

# reconcile: work out whether a job from a previous watcher is still running.
# Called once at startup, before the poll loop.
#
# A backgrounded job is not a child of this process -- it survived the watcher
# that started it. So a pid file is a claim to be verified against the kernel,
# never trusted on its own.

reconcile() {
  local pid
  
  if [ ! -f "$STATE/job.pid" ]; then
    echo "reconcile: idle"
    return 0
  fi

  pid="$(cat "$STATE/job.pid")"

  if alive "$pid"; then
    echo "reconcile: adopted $(cat "$STATE/job.name") (pid $pid)"
    return 0
  fi

  echo "reconcile: cleaning stale $(cat "$STATE/job.name") (pid $pid)"
  rm -f "$STATE/job.pid" "$STATE/job.name"
}
run_loop() {
  local poll="${FARHAND_POLL:-30}"
  reconcile
  echo "watcher up (poll ${poll}s)"
  while true; do
    tick
    sleep "$poll"
  done
}

case "${1:-}" in
  start)  start "${2:?usage: watcher.sh start <engine> <job>}" \
                "${3:?usage: watcher.sh start <engine> <job>}" ;;
  status) status ;;
  run) run_loop ;;
  *) echo "usage: watcher.sh {start <engine> <job>|status}" >&2; exit 2 ;;
esac

